// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Tema1;

import java.util.List;

/************************************************************/
/**
 * 
 */
public class Order {
	/**
	 * 
	 */
	public double totalPrice;

	public List<Ticket> tickets;
	
	public Account account;
	
	
	public Order(List<Ticket> tickets) {
		super();
		this.tickets = tickets;
		
		this.totalPrice = tickets.stream()
				.mapToDouble(t -> t.price)
				.sum();
	}
	
	
};
